### PR TITLE
Add support for Minecraft 1.16.5

### PR DESCRIPTION
**Pull request by intact**

### CODE REVIEW

**Comment by DomiIRL** [comment]
I really want this 1.16.5 version but I won't merge it into the master branch.
So I am going to create a new branch based of your pull request so I have it seperated from the 1.17.1 version ^^

But testing it I noticed a little problem.
When the anchor explodes the endermites that are spawned, instantly despawn/die.

**Comment by intact** [comment]
Fixed endermite spawning, but you probably want to add check for GameRules.DO_MOB_SPAWNING. :)

PS: You can create 1.16.5 branch and i can change base branch for this pull request to that one.

**Comment by DomiIRL** [comment]
I haven't thought about this gamerule yet. 
I'll add this check to this and to the 1.17 version.

Also about the branch, its easier if I just create the branch with all your changes already in it instead of changing the pr target :)

**Comment by DomiIRL** [comment]
So now that we are finished with all of that I think I'll close this pr and clone it into a new branch

**Comment by DomiIRL** [comment]
Thank you really much for your work! :)

**Pull request closed without merging**
